"""
Generate hvm_segments.csv — HVM product is about romantic attraction and succeeding with women.
5 MECE segments covering every man who wants to attract, date, and build romantic success.
"""
import pandas as pd
from pathlib import Path

ROWS = [

# ═══════════════════════════════════════════════════════════════════════════════
# SEGMENT A: The Invisible Romantic (35%)
# Has real qualities but women don't see him as a romantic option.
# Core question: Why am I good enough to rely on but not good enough to want?
# ═══════════════════════════════════════════════════════════════════════════════
{
"segment_id": "A",
"segment_name": "The Invisible Romantic",
"market_share_pct": "35%",
"baseline_description": "Kind, stable, emotionally available, good provider — but romantically invisible. Women confide in him, lean on him, call him a great friend — and then choose someone else. He has everything a relationship requires except the one thing that makes a woman want to be in one with him: genuine romantic desire directed at him.",
"core_question": "Why am I good enough to rely on but not good enough to want?",

"trigger_type": "Chronic friendzoning",
"trigger_description": "Has been explicitly told 'I see you as a friend' or watches the pattern repeat across multiple women he's invested in. He does everything right — is present, listens, invests time — and gets placed firmly in the support category every time.",
"timing_window": "Within 2 weeks of being friendzoned or recognising the pattern clearly",
"buyable_window": "0–3 weeks",
"sweet_spot_months_post_event": "0–2 weeks",
"reddit_communities": "r/dating_advice, r/AskMen, r/socialskills, r/malementalhealth",
"search_queries": "why am I always the friend, how to get out of the friend zone, nice guy vs high value man, how to make women see you romantically",
"content_channels": "Hamza Ahmed, dating advice YouTube, red pill adjacent (intercept here)",
"converting_hook": "She doesn't put you in the friend zone. She puts herself in the category of women who only see you one way — and you can change what category that is.",
"testimonial_type": "I was the guy women cried to about other men. Eighteen months later I had two women pursuing me for the first time in my adult life.",
"ad_campaign_angle": "Target men consuming friendzone and nice guy dating content. Intercept before red pill capture — this is where the radicalization pipeline starts.",
"landing_page_angle": "You're not in the friend zone because you're too kind. You're there because you've never learned to signal that you're a man she'd want to be with romantically — and that's learnable.",
"product_fit": "Identity and attraction framework — shifts what he projects, not what he is. Preserves warmth while building genuine masculine presence.",
"special_notes": "⚠️ HIGHEST RED PILL RISK. This is where men get captured by TRP/incel content. Must offer the understanding of what women respond to without the bitterness conclusion. Messaging must be warmth-preserving.",
"blocker_1": "You either have chemistry or you don't — attraction can't be manufactured and no course creates it",
"blocker_2": "If I change who I am to attract her, she'll be attracted to a fake version of me — not me",
"blocker_3": "She already knows me. No mindset shift makes her suddenly see me differently after years of this.",
"blocker_4": "The real issue is I'm not tall or physically attractive enough — friendzoning is about looks first",
"blocker_5": "I've been in the friend zone so many times I think this is just who I am with women",
"jtbd_type_1": "Emotional", "jtbd_1": "Stop being the man women emotionally rely on and start being the man they emotionally want",
"jtbd_type_2": "Functional", "jtbd_2": "Understand the exact signals that make a woman categorise a man as a romantic option vs a support figure — and change which category I'm in",
"jtbd_type_3": "Social", "jtbd_3": "Be introduced by women to their friends as 'the man I'm seeing' — not 'my really close friend'",
"jtbd_type_4": "Emotional", "jtbd_4": "Replace the quiet resentment of being chosen last with the confidence of being genuinely chosen first",
"jtbd_type_5": "Functional", "jtbd_5": "Learn to express romantic interest in a way that doesn't feel desperate, weird, or kill the entire dynamic",
},

{
"segment_id": "A",
"segment_name": "The Invisible Romantic",
"market_share_pct": "35%",
"baseline_description": "Kind, stable, emotionally available, good provider — but romantically invisible. Women confide in him, lean on him, call him a great friend — and then choose someone else. He has everything a relationship requires except the one thing that makes a woman want to be in one with him: genuine romantic desire directed at him.",
"core_question": "Why am I good enough to rely on but not good enough to want?",

"trigger_type": "Dating app failure",
"trigger_description": "Months of swiping with almost no matches, poor conversations, or ghosted after matching. Better on paper than the men succeeding — better job, kinder, more serious — but invisible or passed over on apps where he thought his real qualities would show.",
"timing_window": "Within 2 weeks of deleting apps or hitting the wall after 3+ months of minimal results",
"buyable_window": "0–3 weeks",
"sweet_spot_months_post_event": "0–2 weeks",
"reddit_communities": "r/Tinder, r/dating_advice, r/AskMen, r/OnlineDating",
"search_queries": "why can't I get matches on Tinder, dating apps not working for average guys, high value man dating profile, how to be more attractive to women",
"content_channels": "Coach Kyle, Better Bachelor, How to Beast, dating advice YouTube",
"converting_hook": "The app doesn't show your value. It shows your signal. You've built the value — here's how to change the signal.",
"testimonial_type": "I had 4 matches in 8 months on three different apps. Six months into this I had consistent conversations with women I was genuinely excited about.",
"ad_campaign_angle": "Target men 25–40 who have recently quit or complained about dating apps. Retarget from dating failure search keywords. Never position as a dating app course — position as identity transformation that makes apps a secondary benefit.",
"landing_page_angle": "The app just shows who you are. The problem isn't your face — it's what you're projecting. That's fixable.",
"product_fit": "Presence and identity modules change what he communicates before he changes anything physical. Direct product fit.",
"special_notes": "High keyword overlap: 'how to attract women' 14.8K/mo Stable, 'how to get a girlfriend' 22.2K/mo Stable. Broad market validation.",
"blocker_1": "Dating apps are broken for average men — it's an algorithmic problem, not something I can fix about myself",
"blocker_2": "Women on apps only want tall, rich, or extremely handsome men — no identity shift changes that filter",
"blocker_3": "I'd need to completely change my appearance to get results — no mindset work fixes what women see first",
"blocker_4": "The men succeeding on apps are using pickup tactics I don't want to use and don't respect",
"blocker_5": "Going off apps to meet women IRL is worse — at least on apps I'm visible to someone, even if they don't match",
"jtbd_type_1": "Functional", "jtbd_1": "Have consistent conversations with women I'm genuinely interested in — not occasional low-quality matches I don't know what to do with",
"jtbd_type_2": "Emotional", "jtbd_2": "Stop opening the app and feeling like my worth is being scored by strangers on a thumbnail — approach from a different place",
"jtbd_type_3": "Social", "jtbd_3": "Be the kind of profile women screenshot and message their friends about — not the 'should I even reply?' guy",
"jtbd_type_4": "Functional", "jtbd_4": "Understand what women actually respond to when evaluating men — and change what I project accordingly, not just what I look like",
"jtbd_type_5": "Emotional", "jtbd_5": "Feel like the dating market is something I can actually navigate — not something that has already decided I don't qualify",
},

{
"segment_id": "A",
"segment_name": "The Invisible Romantic",
"market_share_pct": "35%",
"baseline_description": "Kind, stable, emotionally available, good provider — but romantically invisible. Women confide in him, lean on him, call him a great friend — and then choose someone else. He has everything a relationship requires except the one thing that makes a woman want to be in one with him: genuine romantic desire directed at him.",
"core_question": "Why am I good enough to rely on but not good enough to want?",

"trigger_type": "Good on paper, not chosen",
"trigger_description": "Multiple women have told him he's 'great but not for me' — or he sees the pattern: she's interested enough to meet, enjoy the time, and then go quiet. He has all the attributes he was told matter. None of them appear to be converting to romantic interest.",
"timing_window": "After the third or fourth 'you're great but...' or recognising the pattern across multiple women",
"buyable_window": "0–4 weeks",
"sweet_spot_months_post_event": "1–2 weeks",
"reddit_communities": "r/AskMen, r/AskMenOver30, r/dating_advice, r/selfimprovement",
"search_queries": "why do women say I'm great but not date me, how to be more attractive to women, what makes a high value man to women, why am I not getting results despite doing everything right",
"content_channels": "Dating advice YouTube, Hamza Ahmed, AskMen community threads",
"converting_hook": "There's a difference between having value and projecting it. You've built the value. Here's what you're not projecting.",
"testimonial_type": "Every woman I dated said I was perfect — for someone else. I finally understood why they all meant someone else, and what I was missing.",
"ad_campaign_angle": "Men 28–42 consuming 'why am I single' and 'what women find attractive' content. Key entry point for men who have done self-improvement and still have no results.",
"landing_page_angle": "You're not failing because of what you lack. You're failing because of what you're not communicating. That's fixable.",
"product_fit": "Identity and standards framework — changes the signal, not the substance. Perfect product fit for this trigger.",
"special_notes": "Critical entry point for men who've tried self-improvement without romantic results — the 'I've done everything right' audience. Very high frustration = very high buying intent.",
"blocker_1": "I've already improved everything I can improve — what's left is just genetics and what I look like",
"blocker_2": "Women say 'you're great but' as a polite rejection — it doesn't point to anything genuinely fixable",
"blocker_3": "The men she chooses instead have things I genuinely don't have — looks, height, status, confidence I can't fake",
"blocker_4": "If I have to change myself to attract someone, that means she never liked the real me anyway",
"blocker_5": "I've been told this so many times I've stopped believing there's actually something I can do about it",
"jtbd_type_1": "Emotional", "jtbd_1": "Stop being the man women respect and start being the man women actively want — feel that shift as a real thing",
"jtbd_type_2": "Functional", "jtbd_2": "Identify the specific thing I'm not projecting that women respond to as romantic attraction — and actually change it",
"jtbd_type_3": "Social", "jtbd_3": "Have women describe me to their friends as attractive and desirable — not as 'such a great guy'",
"jtbd_type_4": "Emotional", "jtbd_4": "Replace the exhausting loop of 'am I enough' with a settled confidence that comes from understanding what's actually happening",
"jtbd_type_5": "Functional", "jtbd_5": "Go from being considered to being chosen — consistently, not as a lucky exception",
},

# ═══════════════════════════════════════════════════════════════════════════════
# SEGMENT B: "Why Her, Not Me?" — The Betrayed (25%)
# Painful moment where a worse man was chosen. His model of attraction is broken.
# Core question: If she wanted that, what was I even building toward?
# ═══════════════════════════════════════════════════════════════════════════════
{
"segment_id": "B",
"segment_name": "Why Her, Not Me",
"market_share_pct": "25%",
"baseline_description": "A specific painful moment broke his model of what women want. He was cheated on, left for someone he sees as worse, or watched the pattern repeat enough times that it stopped being random. The story he was told about what makes a man worth choosing has failed him — publicly and painfully. Now he needs to understand what actually happened before it happens again.",
"core_question": "If she wanted that, what was I even building toward?",

"trigger_type": "Cheated on or left for someone worse",
"trigger_description": "She chose someone he sees as objectively inferior — less kind, less stable, less reliable. He did everything right and still lost. His fundamental model of what women respond to has been broken by a real, visible event.",
"timing_window": "2–8 weeks post-discovery, after the initial shock has passed",
"buyable_window": "2–8 weeks",
"sweet_spot_months_post_event": "3–6 weeks",
"reddit_communities": "r/AskMen, r/malementalhealth, r/dating_advice, r/survivinginfidelity (crossover)",
"search_queries": "why do women leave good men for bad ones, why did she choose him over me, women attracted to bad boys, how to understand attraction, high value man after betrayal",
"content_channels": "Red pill adjacent (primary intercept point), Hamza Ahmed as bridge creator, self-improvement after breakup content",
"converting_hook": "What happened to you isn't a mystery. It's a pattern — and once you understand it, you'll never be blindsided by it again.",
"testimonial_type": "She left me for a man who treated her worse in every measurable way. Two years later I understand exactly why that happened — and I've never been more attractive or more confident with women.",
"ad_campaign_angle": "Men 24–40 consuming betrayal and 'why women choose bad men' content. INTERCEPT BEFORE RED PILL CAPTURE — this is the single most dangerous radicalization funnel point.",
"landing_page_angle": "The man she chose told you something real about what she was actually attracted to. Here's how to understand it — without becoming him or becoming bitter.",
"product_fit": "Identity and masculine presence as the alternative to red pill bitterness. Must provide the real explanation — not a softened dismissal — to compete with TRP content.",
"special_notes": "⚠️ HIGHEST RADICALIZATION RISK. Reddit data: 'On the verge of going full incel', 'How do I stop resenting women'. Product must give the actual mechanism of attraction — not platitudes — or it loses to red pill content that also gives a mechanism (even if a broken one).",
"blocker_1": "Women don't know what they want — any framework trying to explain their choices is just rationalising chaos",
"blocker_2": "The only real lesson here is that good men finish last and I need to stop being one",
"blocker_3": "I need time to process this — not another course telling me to be better",
"blocker_4": "Understanding why it happened won't prevent it from happening again with the next woman",
"blocker_5": "High value man is just the red pill rebranded — same conclusion about women, nicer language",
"jtbd_type_1": "Emotional", "jtbd_1": "Actually understand why she made that choice — not to excuse it, but to stop being blindsided by how attraction works",
"jtbd_type_2": "Functional", "jtbd_2": "Build genuine masculine presence that makes women respond to me the way they responded to him — without becoming someone I wouldn't respect",
"jtbd_type_3": "Social", "jtbd_3": "Be the man in every room that women move toward — not the one they're comfortable with but not drawn to",
"jtbd_type_4": "Emotional", "jtbd_4": "Process the rage and confusion without letting it harden into bitterness that defines what I become",
"jtbd_type_5": "Functional", "jtbd_5": "Go from being a man women feel safe with to a man women genuinely desire — and hold both at the same time",
},

{
"segment_id": "B",
"segment_name": "Why Her, Not Me",
"market_share_pct": "25%",
"baseline_description": "A specific painful moment broke his model of what women want. He was cheated on, left for someone he sees as worse, or watched the pattern repeat enough times that it stopped being random. The story he was told about what makes a man worth choosing has failed him — publicly and painfully. Now he needs to understand what actually happened before it happens again.",
"core_question": "If she wanted that, what was I even building toward?",

"trigger_type": "Repeatedly ghosted after real investment",
"trigger_description": "Not one bad experience — a pattern. He invests genuinely in a connection, things feel real and mutual, and then she disappears without explanation. Third or fourth time this has happened. He can't explain it and it's eroding his ability to invest in anything new.",
"timing_window": "After the 3rd or 4th genuine ghosting — pattern recognition moment",
"buyable_window": "0–3 weeks",
"sweet_spot_months_post_event": "0–2 weeks",
"reddit_communities": "r/dating_advice, r/Tinder, r/AskMen, r/OnlineDating",
"search_queries": "why do women ghost good men, being ghosted after great dates, why does she lose interest after things go well, why do women go cold suddenly",
"content_channels": "Dating advice YouTube, male dating psychology channels",
"converting_hook": "You're not being ghosted because you're a bad option. Something you do after she gets close changes her perception of you — and that's completely fixable.",
"testimonial_type": "I invested in four women in one year. Every single one disappeared at a different stage. I now know exactly where the signal broke in each case. It's been 14 months since I was ghosted.",
"ad_campaign_angle": "Men consuming 'why she pulled away' and 'why she went cold' content. 'Why women ghost good men' has significant search volume and high emotional intensity.",
"landing_page_angle": "The ghost isn't random. Something specific changed in how you showed up after she got closer. Here's what that is and how to stop doing it.",
"product_fit": "Attraction and presence modules — he's projecting something different after investment that triggers pull-back. Direct product fit.",
"special_notes": "Massive underserved search category. 'Why does she lose interest' / 'why do women go cold' — huge volume, very high frustration, very high commercial intent.",
"blocker_1": "Women ghost because they're emotionally immature — this is a dating culture problem, not something about me",
"blocker_2": "Ghosting is normal now — no framework changes the fact that women have infinite options and zero accountability",
"blocker_3": "I know why I was ghosted — I just wasn't physically attractive enough for her to justify continuing",
"blocker_4": "Any advice that tells me to be 'less available' or 'more aloof' is manipulation — I won't change who I am for that",
"blocker_5": "I've already tried being less available / more confident / texting less and nothing has changed",
"jtbd_type_1": "Functional", "jtbd_1": "Understand exactly what signal I send after she gets close that makes her pull back — and permanently stop sending it",
"jtbd_type_2": "Emotional", "jtbd_2": "Stop treating every promising connection as a potential last chance and start approaching from genuine abundance",
"jtbd_type_3": "Social", "jtbd_3": "Be the man women want to tell their friends about — not the one they quietly move on from",
"jtbd_type_4": "Functional", "jtbd_4": "Know how to build genuine investment over time — hold her attention and the dynamic develops rather than dying",
"jtbd_type_5": "Emotional", "jtbd_5": "Replace the specific dread of 'things going well followed by the familiar quiet fade' with genuine confidence that it won't happen again",
},

{
"segment_id": "B",
"segment_name": "Why Her, Not Me",
"market_share_pct": "25%",
"baseline_description": "A specific painful moment broke his model of what women want. He was cheated on, left for someone he sees as worse, or watched the pattern repeat enough times that it stopped being random. The story he was told about what makes a man worth choosing has failed him — publicly and painfully. Now he needs to understand what actually happened before it happens again.",
"core_question": "If she wanted that, what was I even building toward?",

"trigger_type": "Watching the wrong man win — repeatedly",
"trigger_description": "Hasn't been personally betrayed but has observed the pattern across enough situations that he can no longer dismiss it. Kinder men, better men, more reliable men — consistently passed over for men who display something he doesn't. He's looking for a real explanation, and the red pill is offering one.",
"timing_window": "After observing the pattern 3+ times — building frustration over weeks or months",
"buyable_window": "2–6 weeks from first serious engagement",
"sweet_spot_months_post_event": "Ongoing — content-led entry",
"reddit_communities": "r/AskMen, r/dating_advice, r/malementalhealth, r/becomeaman",
"search_queries": "why do women choose jerks, nice guys vs bad boys, red pill explained, what makes a man attractive to women, high value man traits",
"content_channels": "Red pill adjacent YouTube (primary intercept), philosophy/psychology channels, Hamza Ahmed as the bridge",
"converting_hook": "The men getting results aren't cruel men. They're doing something real that you're not — and it has nothing to do with treating women badly.",
"testimonial_type": "I spent two years angry at women for their choices. Then I realised I was studying the wrong lesson. Understanding what actually drives attraction changed everything — and I didn't have to become someone I wouldn't respect.",
"ad_campaign_angle": "Intercept men actively consuming red pill and 'why women choose bad boys' content. The offer must provide a REAL explanation — not a dismissal of what he's observed — to compete with TRP content that also provides a mechanism.",
"landing_page_angle": "There's a real pattern behind who women choose. It's not cruelty, or looks, or luck. Here's the actual mechanism — and here's how to build it.",
"product_fit": "Identity and masculine energy framework — gives the real explanation without the red pill conclusion. Must intellectually satisfy, not just emotionally reassure.",
"special_notes": "Product must give a REAL mechanism — not just 'be confident' or 'love yourself'. He's observed something true and will reject soft answers. The red pill wins here because it offers specificity. We must offer better specificity.",
"blocker_1": "Any explanation that doesn't acknowledge what I've observed in women's choices is cope — I've seen the data",
"blocker_2": "High value man is just the red pill with better branding — same conclusion, same advice, different package",
"blocker_3": "You're telling me to become more like the men I don't respect to get results — that's the wrong direction",
"blocker_4": "I understand the theory — I've consumed all of it. Knowing doesn't change how I show up automatically",
"blocker_5": "If building attraction means competing with men who lie and manipulate, I don't want to win by those rules",
"jtbd_type_1": "Emotional", "jtbd_1": "Understand the actual mechanism of attraction — what makes women desire certain men — without needing bitterness as the price of admission",
"jtbd_type_2": "Functional", "jtbd_2": "Build the qualities women respond to in those men — without becoming someone I wouldn't respect",
"jtbd_type_3": "Social", "jtbd_3": "Be the man in my circle that women naturally gravitate toward — without performing anything or pretending not to care",
"jtbd_type_4": "Emotional", "jtbd_4": "Release the anger about what I've observed and build something from it — rather than letting it define my view of women",
"jtbd_type_5": "Functional", "jtbd_5": "Identify exactly what I'm doing that signals low romantic value to women — specific, concrete, fixable",
},

# ═══════════════════════════════════════════════════════════════════════════════
# SEGMENT C: The Re-Entrant (20%)
# Back in the dating market after a gap or starting seriously for the first time.
# Core question: How do I start — or restart — from here?
# ═══════════════════════════════════════════════════════════════════════════════
{
"segment_id": "C",
"segment_name": "The Re-Entrant",
"market_share_pct": "20%",
"baseline_description": "Back in the dating market after a significant gap — end of a long relationship, divorce, or simply never having dated with intention before. The landscape has changed. Apps exist. Norms are different. He doesn't know what women respond to now and feels behind in a world that moved without him.",
"core_question": "How do I start — or restart — from here without looking like I have no idea what I'm doing?",

"trigger_type": "Post-divorce or long-term relationship end",
"trigger_description": "Partnership of 3–12 years has ended. The structure that organised his romantic identity is gone. He's re-entering a dating landscape that barely resembles the one he left — apps, different norms, women his age with different expectations — and needs a framework for the man he's going to be now.",
"timing_window": "3–8 months post-separation — after acute grief, before settling into a new mediocre normal",
"buyable_window": "3–12 months post-separation",
"sweet_spot_months_post_event": "6–10 weeks post-separation",
"reddit_communities": "r/AskMenOver30, r/dating_advice, r/Divorce (crossover), r/selfimprovement",
"search_queries": "how to start dating again after divorce, dating in your 30s 40s, how to attract women after long relationship, starting over romantically at 35, high value man after breakup",
"content_channels": "AskMenOver30 community, self-improvement after breakup content, Stoicism channels",
"converting_hook": "The man you were before that relationship knew how to attract a woman. You haven't lost that — you just forgot what it felt like to have it working.",
"testimonial_type": "I was married for 11 years. Divorced at 38. Dating felt like a foreign language. A year later I'm with a woman who pursues me in a way my ex never did.",
"ad_campaign_angle": "Men 30–50 consuming divorce recovery and 're-entering the dating market' content. One of the highest-intent, highest-urgency entry points in the entire funnel.",
"landing_page_angle": "You don't have to pretend the relationship didn't happen. The man you became through it is more attractive than the man who started it. Here's how to show that.",
"product_fit": "Full identity and attraction framework — he's rebuilding a romantic identity from scratch. Needs the whole thing and is highly motivated to use it.",
"special_notes": "'How to reinvent yourself' 5.4K/mo Rising. 'How to attract women after divorce' is strong commercial search signal. Highest urgency and motivation of any entry point after Segment D.",
"blocker_1": "I'm too old and out of practice — women my age have options and I'm not competitive in the current market",
"blocker_2": "Dating apps barely existed when I was last single — I have no idea how any of this works now",
"blocker_3": "I have kids, financial obligations, and less time — I'm not an attractive option for most women",
"blocker_4": "My ex was my only serious relationship — maybe I never really knew how to attract women and just got lucky",
"blocker_5": "I don't trust my own judgment about women after what happened in that relationship",
"jtbd_type_1": "Emotional", "jtbd_1": "Feel genuinely desirable again — not like a man working hard to appear desirable to someone who might settle",
"jtbd_type_2": "Functional", "jtbd_2": "Understand how to attract women in the modern dating context with the actual life circumstances I have — not some theoretical clean-slate version",
"jtbd_type_3": "Social", "jtbd_3": "Date from a position of genuine confidence in what I bring — not apologising for my age, history, or circumstances",
"jtbd_type_4": "Emotional", "jtbd_4": "Stop seeing my age and history as liabilities and start seeing what they genuinely signal to the right woman",
"jtbd_type_5": "Functional", "jtbd_5": "Know how to navigate early dating — the signals, the timing, the pace — without guessing and getting it wrong",
},

{
"segment_id": "C",
"segment_name": "The Re-Entrant",
"market_share_pct": "20%",
"baseline_description": "Back in the dating market after a significant gap — end of a long relationship, divorce, or simply never having dated with intention before. The landscape has changed. Apps exist. Norms are different. He doesn't know what women respond to now and feels behind in a world that moved without him.",
"core_question": "How do I start — or restart — from here without looking like I have no idea what I'm doing?",

"trigger_type": "Never dated seriously — starting now",
"trigger_description": "Focused on career, academics, or was simply too avoidant to date with intention. Now in his late 20s or 30s and genuinely wants a relationship or romantic success. Has almost no framework for how attraction works and feels conspicuously behind peers who have years of experience he doesn't.",
"timing_window": "Usually triggered by a milestone (30, 35) or watching peers in relationships he wants",
"buyable_window": "4–8 weeks from first serious engagement",
"sweet_spot_months_post_event": "Ongoing — content-led entry",
"reddit_communities": "r/AskMen, r/dating_advice, r/selfimprovement, r/socialskills",
"search_queries": "dating advice for men who have never dated, how to get a girlfriend for the first time, how to be more attractive, how to start dating in your 30s, dating basics for men",
"content_channels": "Self-improvement channels, dating advice beginner content, AskMen threads",
"converting_hook": "Late starts go further when they're built on identity — not on catching up to men who've been playing a different game.",
"testimonial_type": "I was 31 and had never had a relationship last more than a few months. I wasn't broken — I just hadn't understood the first thing about what I was actually communicating to women.",
"ad_campaign_angle": "Men 27–38 consuming 'why have I never had a girlfriend' and 'dating for beginners' content. Shame trigger — framing must normalise and never pathologise.",
"landing_page_angle": "Starting later means you get to build this right from the beginning — rather than unlearning years of bad patterns like men who started early.",
"product_fit": "Foundation modules — identity, standards, attraction fundamentals. He needs the basics done right the first time.",
"special_notes": "High shame trigger. Never position as remedial or catching-up. The late start can be reframed as an advantage: he's building intentionally, not accidentally.",
"blocker_1": "If I haven't figured this out by now, I probably never will — this might just be who I am",
"blocker_2": "Women can sense inexperience — they'll see straight through me and it will make everything worse",
"blocker_3": "Men who are good with women started developing this in their teens — I've missed the formative window",
"blocker_4": "I'm probably just too socially awkward for any of this to be genuinely fixable",
"blocker_5": "A course gives me shortcuts without the experience other men have — I'll seem like I'm performing something I don't actually have",
"jtbd_type_1": "Emotional", "jtbd_1": "Stop feeling ashamed of where I'm starting from and feel genuinely excited about what I'm building toward",
"jtbd_type_2": "Functional", "jtbd_2": "Understand the fundamentals of how romantic attraction actually works — so I stop making the same invisible mistakes without knowing why",
"jtbd_type_3": "Social", "jtbd_3": "Date with the confidence of someone who knows what he's doing — not the constant low-grade anxiety of someone hoping not to get found out",
"jtbd_type_4": "Functional", "jtbd_4": "Build a genuine identity and presence that women respond to — from the ground up, done right the first time",
"jtbd_type_5": "Emotional", "jtbd_5": "Believe that starting late is an actual advantage rather than a permanent deficit I'll never fully close",
},

{
"segment_id": "C",
"segment_name": "The Re-Entrant",
"market_share_pct": "20%",
"baseline_description": "Back in the dating market after a significant gap — end of a long relationship, divorce, or simply never having dated with intention before. The landscape has changed. Apps exist. Norms are different. He doesn't know what women respond to now and feels behind in a world that moved without him.",
"core_question": "How do I start — or restart — from here without looking like I have no idea what I'm doing?",

"trigger_type": "Returns to dating after years of focus elsewhere",
"trigger_description": "Put relationships on the back burner for career, business, or personal goals — now has stability and wants to build a romantic life. Confident in other areas, but feels genuinely inexperienced with women relative to where he is in life. The gap between his professional self-image and his romantic inexperience is uncomfortable.",
"timing_window": "When career or life chapter stabilises enough to make relationships feel possible and priority",
"buyable_window": "2–6 weeks from first serious engagement",
"sweet_spot_months_post_event": "Ongoing — content-led",
"reddit_communities": "r/AskMen, r/AskMenOver30, r/selfimprovement, r/getdisciplined",
"search_queries": "how to attract women in your 30s, dating advice for successful men, how to be more attractive to women, high value man romance, masculine energy attraction",
"content_channels": "Alex Hormozi adjacent, high-performance content, Hamza Ahmed",
"converting_hook": "The discipline that built your career works in attraction too — once you know what to actually build.",
"testimonial_type": "I built a business and a career and never made time for relationships. At 34 I started from close to scratch — but knowing how to build things meant I built this fast.",
"ad_campaign_angle": "Successful men 28–42 who are strong in one area and underdeveloped in romance. 'I have my life together but not this' is a strong identity frame.",
"landing_page_angle": "You know how to build things. You just haven't applied that to this yet. Here's the framework.",
"product_fit": "Identity and attraction modules framed as learnable, buildable skills — not mysterious or genetic. Speaks to his builder's mindset.",
"special_notes": "This segment is highly receptive to framework/system framing. He thinks in systems. 'Masculine energy attraction' 3.6K/mo Rising is a keyword that maps directly.",
"blocker_1": "I've spent years building other things — relationships should come naturally at this point, not require a system",
"blocker_2": "Women can sense that I'm more experienced in business than in this — it's a real disadvantage I can't close quickly",
"blocker_3": "Most relationship advice is targeted at younger men or men without my context — it's not relevant",
"blocker_4": "I don't have time to invest in dating as a project — I need it to work efficiently or not at all",
"blocker_5": "The men who teach attraction don't look like the men I'd take professional advice from — credibility gap",
"jtbd_type_1": "Functional", "jtbd_1": "Apply the same strategic discipline I use in my career to building genuine romantic success — with a real framework, not trial and error",
"jtbd_type_2": "Social", "jtbd_2": "Be with a woman who is genuinely attracted to all of me — not just the professional parts — and feel that difference",
"jtbd_type_3": "Emotional", "jtbd_3": "Close the gap between who I am in my career and who I am in romance — they should feel like the same person",
"jtbd_type_4": "Functional", "jtbd_4": "Understand the specific things high-value women look for beyond career success — and build those deliberately",
"jtbd_type_5": "Social", "jtbd_5": "Have a relationship that other people look at and understand — not something I'm embarrassed about given everything else I've built",
},

# ═══════════════════════════════════════════════════════════════════════════════
# SEGMENT D: The Staller (15%)
# Gets started but can't convert. Women lose interest, or he can't close.
# Core question: Why does it start well and then fall apart every time?
# ═══════════════════════════════════════════════════════════════════════════════
{
"segment_id": "D",
"segment_name": "The Staller",
"market_share_pct": "15%",
"baseline_description": "Can meet women. Gets conversations going. Gets dates. But can't convert — women lose interest after 2–3 dates, or he gets into a relationship and attraction fades fast. He's stuck between meeting women and actually being with women. Close enough to see what he wants, not able to close it.",
"core_question": "Why does it start well and then fall apart every single time?",

"trigger_type": "Women pull away after intimacy or investment",
"trigger_description": "Pattern: connection builds, things feel real, he invests — and she goes cold. Happens after a first date, after sleeping together, after a few weeks of consistent communication. He can attract initial interest but something he does after she gets closer changes the dynamic.",
"timing_window": "After the 3rd or 4th time this pattern plays out — clear recognition moment",
"buyable_window": "1–4 weeks",
"sweet_spot_months_post_event": "1–2 weeks",
"reddit_communities": "r/dating_advice, r/AskMen, r/relationships, r/Tinder",
"search_queries": "why do women pull away when things go well, why does she lose interest after sleeping with me, maintaining attraction in early dating, why she went cold after being interested",
"content_channels": "Dating advice YouTube, male dating psychology channels, attraction and polarity content",
"converting_hook": "She didn't lose interest in you. She lost interest in the version of you that showed up after she got close.",
"testimonial_type": "Every relationship I tried started the same way and ended the same way. Once I understood what I was projecting after she got interested, it stopped happening.",
"ad_campaign_angle": "Men consuming 'why she lost interest' and 'maintaining early attraction' content. Massive search volume for this specific frustration.",
"landing_page_angle": "Attraction isn't maintained by being present. It's maintained by something you stop projecting after she gets close. Here's what that is.",
"product_fit": "Masculine presence and standards modules — the issue is what changes in his behaviour after initial attraction is established. Direct product fit.",
"special_notes": "Enormous underserved search category. 'Why women lose interest' / 'she went cold' has massive commercial intent. Often overlaps with anxious attachment patterns — don't diagnose, describe the behaviour.",
"blocker_1": "Women just get bored — it's their attention span and dating culture, not something about my specific behaviour",
"blocker_2": "Any advice telling me to be less available or play games is manipulation — I won't trade my authenticity for results",
"blocker_3": "I've tried being less available, texting less, being busier — it doesn't change anything meaningful",
"blocker_4": "If she really liked me she wouldn't pull away — she was never actually that interested to begin with",
"blocker_5": "This is just the women I'm meeting — the right woman won't do this",
"jtbd_type_1": "Functional", "jtbd_1": "Understand exactly what I start doing differently after she gets close that changes how she sees me — and permanently stop doing it",
"jtbd_type_2": "Emotional", "jtbd_2": "Feel like I'm the one deciding whether a relationship continues — not waiting anxiously to find out if she'll stay",
"jtbd_type_3": "Social", "jtbd_3": "Be the man women tell their friends they're excited about — not the one they quietly move on from while being polite",
"jtbd_type_4": "Functional", "jtbd_4": "Maintain genuine masculine presence and polarity in early relationship stages — not just when I'm first trying to attract her",
"jtbd_type_5": "Emotional", "jtbd_5": "Stop the specific dread of things going well followed by the familiar quiet fade — replace it with confidence this won't happen again",
},

{
"segment_id": "D",
"segment_name": "The Staller",
"market_share_pct": "15%",
"baseline_description": "Can meet women. Gets conversations going. Gets dates. But can't convert — women lose interest after 2–3 dates, or he gets into a relationship and attraction fades fast. He's stuck between meeting women and actually being with women. Close enough to see what he wants, not able to close it.",
"core_question": "Why does it start well and then fall apart every single time?",

"trigger_type": "Gets first dates, can't convert to second or third",
"trigger_description": "She agreed to meet. The date felt good by any objective measure — good conversation, she was engaged, no obvious disasters. Then silence. No text back. Happens across multiple women. The gap between 'she showed up' and 'she wanted to see me again' is consistent and confusing.",
"timing_window": "After noticing the pattern — 3rd or 4th first date that goes nowhere",
"buyable_window": "0–3 weeks",
"sweet_spot_months_post_event": "0–2 weeks",
"reddit_communities": "r/Tinder, r/dating_advice, r/AskMen, r/OnlineDating",
"search_queries": "why doesn't she text back after a good date, how to get a second date, converting first dates to relationships, how to be more attractive in person vs on profile",
"content_channels": "Dating advice YouTube, dating coach content, in-person attraction content",
"converting_hook": "The first date is an audition. The problem is most men don't know what role they're showing up to play.",
"testimonial_type": "I was going on first dates every week and none of them led anywhere. Once I understood what I was signalling in person versus what my profile communicated, my conversion rate changed completely.",
"ad_campaign_angle": "Men consuming first date advice and 'she didn't text back after the date' content. Very high commercial search intent around date conversion.",
"landing_page_angle": "You got the date — something about you was attractive enough for her to show up. What you're delivering in person isn't matching what she came for. That's a specific, fixable mismatch.",
"product_fit": "Attraction and presence modules — the gap between profile/text and in-person is an identity consistency issue. Clear product fit.",
"special_notes": "Strong search volume around first-date conversion. Often the problem is in-person he becomes uncertain/eager where the profile/text suggested confidence. Presence and identity modules solve this directly.",
"blocker_1": "Dates go nowhere because there's no chemistry — that's not something you can manufacture or learn",
"blocker_2": "I know how to have a good conversation — the problem is she just wasn't that interested",
"blocker_3": "Any 'technique' for converting first dates is manipulation — if she wanted a second date she'd say so",
"blocker_4": "My problem is I get nervous in person — no framework genuinely fixes real anxiety",
"blocker_5": "I'm probably just more attractive on paper than I am in person — my profile is doing better than I can maintain",
"jtbd_type_1": "Functional", "jtbd_1": "Know exactly what to do on a first date that builds attraction rather than just comfortable conversation",
"jtbd_type_2": "Emotional", "jtbd_2": "Show up to first dates feeling like someone worth choosing — not someone managing anxiety and hoping not to disappoint",
"jtbd_type_3": "Social", "jtbd_3": "Have women text their friends about me after a date — not quietly file me in the 'nice but no spark' category",
"jtbd_type_4": "Functional", "jtbd_4": "Convert genuine initial interest into real momentum — know how to move from one date to something that actually continues",
"jtbd_type_5": "Emotional", "jtbd_5": "Stop the specific frustration of a date going 'fine by every measure' and then nothing happening — understand why and fix it",
},

# ═══════════════════════════════════════════════════════════════════════════════
# SEGMENT E: The Upgrader (5%)
# Has dating success but wants better results, better quality, or genuine long-term attraction.
# Core question: How do I attract the kind of woman I actually want to be with?
# ═══════════════════════════════════════════════════════════════════════════════
{
"segment_id": "E",
"segment_name": "The Upgrader",
"market_share_pct": "5%",
"baseline_description": "Has romantic success — gets matches, has relationships, has experience with women. But the women he's attracting aren't the ones he wants, or the relationships he's building don't have the depth and genuine attraction he's looking for. Wants to move from tactical dating success to being genuinely high value to the women he actually wants.",
"core_question": "How do I attract the kind of woman I actually want — not just the women who are available?",

"trigger_type": "Consistently attracting the wrong type of woman",
"trigger_description": "Not failing — but the women who pursue him or respond to him aren't the ones he wants to be with. He has enough success to know he's doing something right, but the pattern of who he attracts tells him he's projecting something that draws the wrong kind of interest.",
"timing_window": "After recognising the pattern across 2–3 relationships or a consistent type of woman he keeps attracting",
"buyable_window": "2–6 weeks from first serious engagement",
"sweet_spot_months_post_event": "Ongoing — content-led",
"reddit_communities": "r/selfimprovement, r/AskMen, r/dating_advice, r/getdisciplined",
"search_queries": "how to attract higher quality women, how to meet quality women for relationships, what makes a man genuinely high value, how to attract the right woman",
"content_channels": "Alex Hormozi adjacent, Hamza Ahmed premium tier, high-performance self-improvement content",
"converting_hook": "Your results tell you something about who you're being — not just about who you're meeting.",
"testimonial_type": "I had no shortage of women. The wrong ones kept finding me. Once I understood why I was projecting that, I attracted the kind of woman I'd actually been looking for.",
"ad_campaign_angle": "Men who have dating experience but are dissatisfied with the quality or type of women they're attracting. Highest LTV segment — already spending on self-improvement, least price-sensitive.",
"landing_page_angle": "You're not failing to attract women. You're attracting exactly the women that match what you're currently projecting. Change the projection, change the result.",
"product_fit": "Identity and standards framework — helps him define what he wants to attract and build the identity that attracts it. Highest premium programme fit.",
"special_notes": "Smallest segment but highest LTV. Already buying content. Best segment for premium and annual programme positioning. 'How to attract higher quality women' is a commercial keyword with strong intent.",
"blocker_1": "Quality women are rare — this is a supply problem in the cities I live in, not something about what I'm projecting",
"blocker_2": "I've already done the self-improvement work. High value man content won't show me anything new.",
"blocker_3": "If I raise my standards I'll end up alone — a real relationship with the wrong person beats an ideal one I never find",
"blocker_4": "Women I'd want are looking for resources and looks I don't have — this isn't an identity problem",
"blocker_5": "I don't need a framework — I need to find the right city, social circle, or context to meet the right women",
"jtbd_type_1": "Functional", "jtbd_1": "Become the kind of man that the women I'm genuinely attracted to actively pursue — not just the women who are available to me",
"jtbd_type_2": "Social", "jtbd_2": "Be in a relationship with a woman I genuinely respect and desire — chosen from real options, not the best available",
"jtbd_type_3": "Emotional", "jtbd_3": "Stop feeling like I'm making the most of what comes to me and start feeling like I'm choosing from what I want",
"jtbd_type_4": "Functional", "jtbd_4": "Understand what genuinely high-value women are attracted to — beyond surface tactics — and build that identity for real",
"jtbd_type_5": "Social", "jtbd_5": "Be seen by the women I most respect as genuinely desirable — not just successful or reliable, but someone they desire",
},

{
"segment_id": "E",
"segment_name": "The Upgrader",
"market_share_pct": "5%",
"baseline_description": "Has romantic success — gets matches, has relationships, has experience with women. But the women he's attracting aren't the ones he wants, or the relationships he's building don't have the depth and genuine attraction he's looking for. Wants to move from tactical dating success to being genuinely high value to the women he actually wants.",
"core_question": "How do I attract the kind of woman I actually want — not just the women who are available?",

"trigger_type": "Relationship loses genuine attraction fast",
"trigger_description": "Gets into relationships but the real mutual attraction fades within 2–4 months. Becomes roommates with benefits. She stops pursuing. He stops feeling desired. Both settle into comfort. Keeps thinking it's about finding the 'right person' but the pattern is too consistent to be only about who he's meeting.",
"timing_window": "After the 2nd or 3rd relationship that starts strong and becomes flat within months",
"buyable_window": "2–8 weeks from first serious engagement",
"sweet_spot_months_post_event": "Ongoing — content-led",
"reddit_communities": "r/relationships, r/AskMen, r/selfimprovement, r/dating_advice",
"search_queries": "how to maintain attraction in a long-term relationship, why does the spark fade, keeping a woman attracted to you, masculine energy in a relationship, how to stop becoming roommates",
"content_channels": "Relationship dynamics content, Hamza Ahmed, masculine energy and polarity channels",
"converting_hook": "Attraction doesn't fade on its own. Polarity fades — and that's something you can maintain.",
"testimonial_type": "Every relationship I had started exciting and ended as comfortable roommates. Now I understand what I was doing in the first few months that killed the dynamic — and my current relationship is different.",
"ad_campaign_angle": "Men consuming 'how to keep her attracted' and 'why do relationships lose spark' content. 'Masculine energy attraction' 3.6K/mo Rising is a direct keyword match.",
"landing_page_angle": "The attraction that got her there doesn't maintain itself. Here's the masculine identity and presence that keeps it alive — in a real, committed relationship.",
"product_fit": "Standards, polarity, and masculine presence modules applied to relationship context. Highest relevance for long-term attraction maintenance.",
"special_notes": "'Masculine energy attraction' 3.6K/mo Rising maps exactly to this trigger. Growing category as more men understand polarity. Premium positioning as relationship deepening, not just initial attraction.",
"blocker_1": "The honeymoon phase ending is universal — attraction fading is inevitable, not a personal failure I can fix",
"blocker_2": "My past relationships went flat because of her — I just need to find the right person and it won't happen",
"blocker_3": "Advice about 'polarity' and 'masculine energy' in relationships is pickup tactics dressed up for LTR — I don't want to manage my partner",
"blocker_4": "I don't want to have to work to maintain attraction — if she's the right person it shouldn't require this much effort",
"blocker_5": "Some relationships stay exciting and some don't — it's about compatibility, not about what I'm doing",
"jtbd_type_1": "Emotional", "jtbd_1": "Be in a relationship where both of us feel genuinely attracted and alive — not just comfortable, habitual, and politely content",
"jtbd_type_2": "Functional", "jtbd_2": "Understand what I start doing after we commit that kills attraction — and stop doing it automatically without thinking",
"jtbd_type_3": "Social", "jtbd_3": "Have a partner who still pursues me and talks about me to her friends after years — not someone who has simply decided to stay",
"jtbd_type_4": "Emotional", "jtbd_4": "Stop the specific dread of watching a genuinely good relationship slowly become polite coexistence — and know how to prevent it",
"jtbd_type_5": "Functional", "jtbd_5": "Know how to maintain masculine presence and genuine standards within a committed relationship — not just to attract her initially",
},

]

COLUMNS = [
    "segment_id", "segment_name", "market_share_pct", "baseline_description", "core_question",
    "trigger_type", "trigger_description", "timing_window", "buyable_window",
    "sweet_spot_months_post_event", "reddit_communities", "search_queries", "content_channels",
    "converting_hook", "testimonial_type", "ad_campaign_angle", "landing_page_angle",
    "product_fit", "special_notes",
    "blocker_1", "blocker_2", "blocker_3", "blocker_4", "blocker_5",
    "jtbd_type_1", "jtbd_1", "jtbd_type_2", "jtbd_2", "jtbd_type_3", "jtbd_3",
    "jtbd_type_4", "jtbd_4", "jtbd_type_5", "jtbd_5",
]

df = pd.DataFrame(ROWS, columns=COLUMNS)
df.to_csv("hvm_segments.csv", index=False, encoding="utf-8-sig")
print(f"✓ Saved {len(df)} rows → hvm_segments.csv")
print(f"Segments: {df['segment_name'].unique().tolist()}")
print(f"Columns: {len(df.columns)}")
