"""
Rebuild male_charisma_mastery.csv:
- Remove Content Naming Moment trigger
- Add 5 blockers and 5 JTBDs per trigger (male marketing psychology framing)
- Add new C2 subsegment: Attraction Plateau (gym-minded high-achiever)
- Columns: all original + blocker_1–5, jtbd_type_1–5, jtbd_1–5
"""

import pandas as pd

ROWS = [
    # ── SEGMENT A: CHRONIC GAP ──────────────────────────────────────────────────
    {
        "segment_id": "A",
        "segment_name": "Chronic Gap",
        "market_share_pct": "40%",
        "baseline_description": "Never developed social confidence — gap has existed for years or decades. Has adapted around it through career focus, avoidance, or digital substitution.",
        "core_question": "Why is this so easy for everyone else?",
        "trigger_type": "Public Rejection",
        "trigger_description": "Specific rejection or visible humiliation crystallises the problem as urgent rather than background noise",
        "timing_window": "Immediate — days to weeks post trigger",
        "buyable_window": "0–4 weeks",
        "sweet_spot_months_post_event": "1–2 weeks",
        "reddit_communities": "r/socialskills, r/selfimprovement, r/dating_advice",
        "search_queries": "why do I freeze up talking to women, how to stop being awkward, approach anxiety fix",
        "content_channels": "Charisma on Command, Hamza Ahmed, HealthyGamerGG",
        "converting_hook": "Problem naming — gives his condition a name and frames it as a skill gap not a character flaw",
        "testimonial_type": "I was always the awkward guy in every room. Now people actually remember when I leave.",
        "ad_campaign_angle": "Target men 22–35 actively searching after rejection event",
        "landing_page_angle": "You've always known something was off. Here's what it is and how to fix it.",
        "product_fit": "One course serves both A and B — heavier on fundamentals and identity building for A",
        "special_notes": "None",
        "blocker_1": "This kind of course only works for people who are already somewhat confident — not someone who has been awkward his whole life",
        "blocker_2": "If I try these techniques and get rejected again, it will prove that nothing will ever work for me",
        "blocker_3": "I've already embarrassed myself — if those people see me acting differently now they'll think I'm fake",
        "blocker_4": "Social skills training makes men come across as try-hard — people can sense when someone is using rehearsed techniques",
        "blocker_5": "I'm afraid that if I invest in this and fail again, I'll have nowhere left to go",
        "jtbd_type_1": "Emotional",
        "jtbd_1": "Stop dreading every time I walk into a room. Feel like someone who belongs there — not someone waiting to be found out",
        "jtbd_type_2": "Functional",
        "jtbd_2": "Approach a woman I'm attracted to without my mind going blank — have actual words come out and not replay the interaction for three days",
        "jtbd_type_3": "Social",
        "jtbd_3": "Be someone people remember and want to talk to again — not the guy others are polite to and then forget",
        "jtbd_type_4": "Functional",
        "jtbd_4": "Have a specific response ready for the next rejection that keeps my dignity and doesn't make things awkward",
        "jtbd_type_5": "Emotional",
        "jtbd_5": "Stop letting one bad moment define how I see myself in every social situation that follows",
    },
    {
        "segment_id": "A",
        "segment_name": "Chronic Gap",
        "market_share_pct": "40%",
        "baseline_description": "Never developed social confidence — gap has existed for years or decades. Has adapted around it through career focus, avoidance, or digital substitution.",
        "core_question": "Why is this so easy for everyone else?",
        "trigger_type": "Dating App Exhaustion",
        "trigger_description": "Months of no matches or no converting dates — tried the lower-stakes digital path and it failed. Now open to deeper work.",
        "timing_window": "Immediate — within weeks of giving up on apps",
        "buyable_window": "0–4 weeks",
        "sweet_spot_months_post_event": "Ongoing",
        "reddit_communities": "r/Tinder, r/hingeapp, r/dating_advice, r/ForeverAlone",
        "search_queries": "why cant i get matches, why do women not respond to me, dating app advice men, am I undateable",
        "content_channels": "How to Beast, dating app breakdown channels, Coach Kyle",
        "converting_hook": "Skill gap reframe — not a looks problem, a presence and personality problem",
        "testimonial_type": "I spent 8 months on Hinge getting nowhere. Turns out I had a presence problem not a face problem.",
        "ad_campaign_angle": "Target men 22–35 searching dating app failure terms",
        "landing_page_angle": "You don't have a looks problem. You have a presence problem.",
        "product_fit": "Same product — fundamentals focus",
        "special_notes": "Strong retargeting opportunity from dating app content consumers",
        "blocker_1": "This is just another version of pickup artist content — it will make me seem fake and manipulative rather than genuinely attractive",
        "blocker_2": "Dating apps are algorithmically rigged to show the same top 20% to everyone — charisma doesn't fix a broken distribution system",
        "blocker_3": "I've already spent money on a photographer and profile reviews and nothing changed — why would this be different",
        "blocker_4": "Women on dating apps are so overwhelmed with options they'll never give someone like me a fair chance regardless of what I learn",
        "blocker_5": "Charisma courses teach generic techniques that every guy who's done one uses — women have seen it all before",
        "jtbd_type_1": "Functional",
        "jtbd_1": "Actually get to a third date. Not just match or get a reply — sit across from someone who wants to be there and feel like something real is starting",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Stop checking my phone hoping for a match and feeling worse about myself every hour I don't get one",
        "jtbd_type_3": "Social",
        "jtbd_3": "Be a man women describe to their friends as genuinely interesting — not just 'a guy I matched with'",
        "jtbd_type_4": "Functional",
        "jtbd_4": "Convert a first date into a second without overanalyzing every message I sent or word I said on the night",
        "jtbd_type_5": "Functional",
        "jtbd_5": "Stop relying on apps entirely — have the confidence to meet women in real life so a phone algorithm doesn't control my dating life",
    },
    {
        "segment_id": "A",
        "segment_name": "Chronic Gap",
        "market_share_pct": "40%",
        "baseline_description": "Never developed social confidence — gap has existed for years or decades. Has adapted around it through career focus, avoidance, or digital substitution.",
        "core_question": "Why is this so easy for everyone else?",
        "trigger_type": "Age Milestone",
        "trigger_description": "Turning 25, 30, or 35 forces a hard audit. The gap stops feeling temporary and starts feeling like a choice.",
        "timing_window": "Immediate — within 30–60 days of milestone birthday",
        "buyable_window": "0–8 weeks",
        "sweet_spot_months_post_event": "0–2 weeks post birthday",
        "reddit_communities": "r/selfimprovement, r/decidingtobebetter, r/AskMen",
        "search_queries": "how to be more confident at 30, how to improve social skills as an adult, self improvement for men",
        "content_channels": "Hamza Ahmed, Better Bachelor, self-improvement content",
        "converting_hook": "Now or never framing — this is the decision point not just another year",
        "testimonial_type": "I was turning 30 and had never felt like I was really in the room. I decided that was the last birthday that felt that way.",
        "ad_campaign_angle": "Target men in the 30–60 day window around milestone birthdays via Meta age targeting",
        "landing_page_angle": "You're at the age where this stops being a phase and becomes a choice.",
        "product_fit": "Same product",
        "special_notes": "Consider birthday-based ad scheduling on Meta",
        "blocker_1": "Learning charisma from a course at 30 will make it feel scripted and unnatural — people will see that it is performed not real",
        "blocker_2": "I've been this way for 30 years — you can't fundamentally rewire a personality at this stage",
        "blocker_3": "Men who suddenly change their behavior at 30 come across as mid-life crisis energy and women can smell the desperation",
        "blocker_4": "Every self-improvement program says it works but the men it works for already had something to work with — I'm starting from zero",
        "blocker_5": "I should be focused on career and finances at this stage — this is the wrong priority for a 30-year-old",
        "jtbd_type_1": "Social",
        "jtbd_1": "Walk into a room at 30 and have people actually notice I am there. Not be the guy who could leave and nobody would know",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Stop having the same internal conversation every birthday where I promise myself things will be different this year",
        "jtbd_type_3": "Functional",
        "jtbd_3": "Have a social circle by 33 that actually reflects who I want to be — not the same drifted school contacts or proximity-only colleagues",
        "jtbd_type_4": "Emotional",
        "jtbd_4": "Feel like I chose this decade instead of letting it happen to me",
        "jtbd_type_5": "Social",
        "jtbd_5": "Be someone that men my age genuinely respect and want to be around — not just tolerated as part of a group",
    },
    {
        "segment_id": "A",
        "segment_name": "Chronic Gap",
        "market_share_pct": "40%",
        "baseline_description": "Never developed social confidence — gap has existed for years or decades. Has adapted around it through career focus, avoidance, or digital substitution.",
        "core_question": "Why is this so easy for everyone else?",
        "trigger_type": "Peer Success Contrast",
        "trigger_description": "A friend or peer with less apparent qualification visibly succeeds romantically or socially. The gap becomes concrete not abstract.",
        "timing_window": "Immediate — within days of the moment",
        "buyable_window": "0–2 weeks",
        "sweet_spot_months_post_event": "0–1 week",
        "reddit_communities": "r/socialskills, r/relationships, r/AskMen",
        "search_queries": "how to be more attractive to women, why does he get girls and I don't, how to develop a magnetic personality",
        "content_channels": "Charisma on Command, social comparison content, self-improvement channels",
        "converting_hook": "Gap concretisation — the gap is real and learnable, not mysterious",
        "testimonial_type": "I watched my less successful friend walk out of a party with her number and I left alone. That was the night I decided something had to change.",
        "ad_campaign_angle": "Target men consuming social comparison and self-improvement content",
        "landing_page_angle": "The gap between you and him isn't luck. It's a learnable skill.",
        "product_fit": "Same product",
        "special_notes": "High emotional urgency — convert quickly",
        "blocker_1": "He is naturally like that — you either have it or you do not and no course can give someone what another person was just born with",
        "blocker_2": "If I try to be like him I'll just look like a knockoff version — and everyone will see I'm copying",
        "blocker_3": "He's extroverted and I'm introverted — charisma training is designed for naturally social people, not for people like me",
        "blocker_4": "This will just make me want things I can't actually have and I'll end up more frustrated than when I started",
        "blocker_5": "Success with women is about looks and money, not charisma — he succeeds because of those things not how he talks",
        "jtbd_type_1": "Social",
        "jtbd_1": "Be the man in the group people naturally pay attention to — not the one standing there watching it happen to someone else",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Stop feeling the specific shame of watching someone with less going for him succeed where I consistently fail",
        "jtbd_type_3": "Functional",
        "jtbd_3": "Have women in my social circle who are genuinely interested in me — not just politely friendly because I'm part of the group",
        "jtbd_type_4": "Social",
        "jtbd_4": "Command the same respect in a room that the most magnetic man there gets — earned through presence, not just performance",
        "jtbd_type_5": "Emotional",
        "jtbd_5": "Replace the thought 'why not me' with something that feels like quiet confidence instead of quiet envy",
    },
    {
        "segment_id": "A",
        "segment_name": "Chronic Gap",
        "market_share_pct": "40%",
        "baseline_description": "Never developed social confidence — gap has existed for years or decades. Has adapted around it through career focus, avoidance, or digital substitution.",
        "core_question": "Why is this so easy for everyone else?",
        "trigger_type": "New City or Job",
        "trigger_description": "Old avoidance tactics don't transfer to a new environment. Forced social exposure with no safety net.",
        "timing_window": "Immediate — within first 3 months of transition",
        "buyable_window": "0–12 weeks",
        "sweet_spot_months_post_event": "2–6 weeks post move",
        "reddit_communities": "r/socialskills, r/moving, r/selfimprovement, city-specific subreddits",
        "search_queries": "how to make friends in a new city, how to be more social, how to build a social circle from scratch",
        "content_channels": "Self-improvement and social skills channels",
        "converting_hook": "Clean slate framing — this is the exact moment to build a different version of yourself",
        "testimonial_type": "I moved to a new city at 28 and decided not to recreate the same quiet version of myself I'd always been.",
        "ad_campaign_angle": "Target men who recently moved or started new jobs via life event targeting",
        "landing_page_angle": "New city. New job. Perfect time to become the version of yourself you've been putting off.",
        "product_fit": "Same product — high overlap with Segment B geographic relocation trigger",
        "special_notes": "Strong life event targeting opportunity on Meta and LinkedIn",
        "blocker_1": "I need to make real impressions right now — a multi-week course is too slow for the urgency of this moment",
        "blocker_2": "Charisma I learn from a course will feel scripted — and people in a new environment with no prior context will see straight through it",
        "blocker_3": "In a new city everyone is busy building their own lives — no amount of charisma makes people who are already settled want new friends",
        "blocker_4": "The social dynamics where I'm going are completely different from anything I've known — generic charisma advice won't translate",
        "blocker_5": "Making friends in your late 20s and 30s requires circumstances not skills — people bond over shared situations, not charm",
        "jtbd_type_1": "Functional",
        "jtbd_1": "Have actual people I can call in this city within three months — not just colleagues I eat lunch with because there is nobody else",
        "jtbd_type_2": "Social",
        "jtbd_2": "Be someone that new people genuinely want to see again — not the new guy who's trying a bit too hard",
        "jtbd_type_3": "Functional",
        "jtbd_3": "Know how to turn acquaintances into real friendships — not just exchange pleasantries and hope proximity does the work",
        "jtbd_type_4": "Emotional",
        "jtbd_4": "Stop dreading the first few months of starting over and feel like someone who knows how to build a life wherever he lands",
        "jtbd_type_5": "Social",
        "jtbd_5": "Build a reputation in this new environment early — before people have already decided what kind of person I am",
    },
    # ── SEGMENT B: RUPTURED MAN ──────────────────────────────────────────────────
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Divorce",
        "trigger_description": "Marriage ended — especially if she initiated or children are involved. Identity built around the role of husband is gone.",
        "timing_window": "9–18 months post divorce",
        "buyable_window": "9–18 months",
        "sweet_spot_months_post_event": "12–15 months",
        "reddit_communities": "r/Divorce, r/ExNoContact, r/AskMenOver30, r/AskMenOver40",
        "search_queries": "how to rebuild confidence after divorce, starting over at 40, how to be attractive again after long marriage",
        "content_channels": "Dr. K, relationship recovery channels migrating toward self-improvement over time",
        "converting_hook": "Transformation narrative — a man who went through exactly this and rebuilt into someone he respects",
        "testimonial_type": "After my divorce I genuinely thought that part of my life was over. It wasn't. It was just starting.",
        "ad_campaign_angle": "Target men 35–52 whose divorce-related posts or searches are 9–18 months old",
        "landing_page_angle": "You're not starting over. You're starting with everything you learned.",
        "product_fit": "Same product — heavier identity and emotional intelligence modules",
        "special_notes": "High-value segment — financially stable and highly motivated. Do not target in the acute grief phase.",
        "blocker_1": "A charisma course is designed for young men learning to date for the first time — not for a 42-year-old man rebuilding after a marriage",
        "blocker_2": "After a divorce there is real grief to process — learning social techniques feels hollow when I'm still emotionally raw",
        "blocker_3": "My kids need to come first — I can't justify time or money on self-improvement right now",
        "blocker_4": "I don't even know if I want to date again — buying this course feels like making a decision I'm not ready to make",
        "blocker_5": "The dating market at 42 has completely changed since I was last in it — I need practical knowledge for my age, not generic charisma",
        "jtbd_type_1": "Emotional",
        "jtbd_1": "Feel like a man again — not someone's ex-husband, not a cautionary tale, just a person who has something real to offer",
        "jtbd_type_2": "Functional",
        "jtbd_2": "Have a first date that goes well enough that she wants to see me again — and feel like I know what I'm doing, not fumbling through it",
        "jtbd_type_3": "Social",
        "jtbd_3": "Walk into a room at 42 as a divorced man and have it be a strength, not something I have to explain or apologize for",
        "jtbd_type_4": "Emotional",
        "jtbd_4": "Stop defining myself by what ended and start building something I'm actually excited about",
        "jtbd_type_5": "Functional",
        "jtbd_5": "Have a framework for dating in my 40s that actually makes sense — not advice designed for 25-year-olds",
    },
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Long-Term Relationship Ending",
        "trigger_description": "Relationship of 3+ years ends. Life was built around her — friends, routines, identity. Now structurally alone.",
        "timing_window": "6–14 months post breakup",
        "buyable_window": "6–14 months",
        "sweet_spot_months_post_event": "9–12 months",
        "reddit_communities": "r/BreakUps, r/ExNoContact, r/selfimprovement",
        "search_queries": "how to find yourself after a long relationship, how to rebuild confidence after breakup, who am I after 5 years together",
        "content_channels": "Dr. K, Charisma on Command — men typically migrate from grief content to self-improvement over 6–9 months",
        "converting_hook": "Emergence framing — the hardest part is over and this is when the real work begins",
        "testimonial_type": "After 5 years I didn't know who I was outside that relationship. That confusion became the most useful thing that ever happened to me.",
        "ad_campaign_angle": "Target men whose breakup posts are 6–14 months old across r/BreakUps and r/ExNoContact",
        "landing_page_angle": "The hardest part is behind you. Now comes the part where you decide who you become.",
        "product_fit": "Same product",
        "special_notes": "Timing is critical — targeting at month 1 or 2 reaches grieving men not ready buyers",
        "blocker_1": "Buying a course to meet someone new means accepting it is over — and I am not sure I am ready to do that",
        "blocker_2": "I've been out of the game for 5 years — the dating landscape has completely changed and I don't understand the rules anymore",
        "blocker_3": "I'm still hoping she'll come back — investing in a course about moving on feels like giving up on that",
        "blocker_4": "After being with one person for years I've forgotten how to be myself around new women — it's not just charisma I need, it's recalibration",
        "blocker_5": "Everyone will see this as rebound energy — I'm worried about coming across as recently heartbroken and desperate",
        "jtbd_type_1": "Functional",
        "jtbd_1": "Go on a date and actually be present — not comparing everything to her, not running the old relationship in my head, just there with someone new",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Stop measuring every new woman against a benchmark that may not even have been real — feel genuinely curious about someone new",
        "jtbd_type_3": "Social",
        "jtbd_3": "Have a version of myself that is separate from the relationship I was in — a person, not just half of a couple that no longer exists",
        "jtbd_type_4": "Functional",
        "jtbd_4": "Be able to talk about my past relationship on a date in a way that doesn't make me seem bitter or unfinished",
        "jtbd_type_5": "Emotional",
        "jtbd_5": "Feel like this chapter ending was the start of something, not just a loss that doesn't have a second act",
    },
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Cheating and Betrayal",
        "trigger_description": "Partner cheated — confidence collapse layered on top of heartbreak. Questions his own judgment, his attractiveness, everything.",
        "timing_window": "9–18 months post discovery",
        "buyable_window": "9–18 months",
        "sweet_spot_months_post_event": "12–18 months",
        "reddit_communities": "r/survivinginfidelity, r/Infidelity, r/ExNoContact",
        "search_queries": "how to rebuild self-worth after being cheated on, how to trust yourself again after betrayal, how to feel attractive again",
        "content_channels": "Dr. K, betrayal trauma content migrating to self-improvement",
        "converting_hook": "Identity reclamation — you trusted your judgment and it was tested. Now rebuild on a foundation that isn't someone else's approval.",
        "testimonial_type": "She cheated and I realised my confidence had been built entirely on her validation. I had to learn to own it for myself.",
        "ad_campaign_angle": "Target men in survivinginfidelity communities whose posts are 9+ months old — not recent",
        "landing_page_angle": "What she did broke your confidence. What you do next builds something that can't be taken away.",
        "product_fit": "Same product — self-worth and trust modules especially relevant",
        "special_notes": "Sensitive messaging required — avoid blame framing. Focus on reclamation not revenge.",
        "blocker_1": "My confidence problem is not about social skills — she broke my trust and no course fixes that",
        "blocker_2": "If I build confidence and she finds out, she'll think she didn't affect me — and I want her to understand what she took from me",
        "blocker_3": "I trusted my judgment completely and got it catastrophically wrong — how can I trust any advice when my instincts failed me this badly",
        "blocker_4": "Any course I buy right now will just be rage-energy that burns off when I calm down — I'll regret making decisions from this emotional state",
        "blocker_5": "Women will sense that I've been hurt and see me as damaged goods — building confidence over it doesn't change what happened to me",
        "jtbd_type_1": "Emotional",
        "jtbd_1": "Feel attractive and worth being with without needing anyone to confirm it — own it from the inside so nobody can take it away from me again",
        "jtbd_type_2": "Functional",
        "jtbd_2": "Identify what I was missing or projecting so I don't repeat the same pattern with someone new",
        "jtbd_type_3": "Social",
        "jtbd_3": "Walk into a room and have people read me as a man who has his life together — not someone who just had the rug pulled out",
        "jtbd_type_4": "Emotional",
        "jtbd_4": "Stop replaying the moment I found out and feeling the physical shame of it — replace it with something that feels like the end of that chapter",
        "jtbd_type_5": "Functional",
        "jtbd_5": "Date again from a position of genuine selection — choosing someone I want, not accepting whoever shows interest because my confidence is low",
    },
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Identity-Losing Relationship",
        "trigger_description": "Gave up friends, hobbies, and personality over the course of a long relationship. Emerged from it not recognising himself.",
        "timing_window": "6–12 months post breakup",
        "buyable_window": "6–12 months",
        "sweet_spot_months_post_event": "8–12 months",
        "reddit_communities": "r/ExNoContact, r/selfimprovement, r/decidingtobebetter",
        "search_queries": "how to find yourself again after a relationship, how to get your personality back, how to stop losing yourself in relationships",
        "content_channels": "Charisma on Command, self-discovery content, Dr. K",
        "converting_hook": "Rediscovery framing — who you were before her is still in there. He didn't disappear, he just got buried.",
        "testimonial_type": "I gave up everything for that relationship. Rebuilding was the first time I actually chose who I wanted to be.",
        "ad_campaign_angle": "Target men posting about losing themselves in a relationship 6–12 months ago",
        "landing_page_angle": "You didn't lose yourself. You just forgot where you left him.",
        "product_fit": "Same product — identity reconstruction modules weighted heavier",
        "special_notes": "Strong emotional resonance — these men often feel deep shame about having lost themselves",
        "blocker_1": "I do not know who I want to become — so I cannot commit to any course because I would just be building a performance not a real person",
        "blocker_2": "My personality was suppressed for so long that I genuinely don't know what is authentic to me anymore — how can I develop it if I don't know what it is",
        "blocker_3": "Learning someone else's system for charisma feels like replacing one mold I was forced into with another one I'm choosing",
        "blocker_4": "My friends have moved on during the years I was in that relationship — I'm not sure I still have the social context to apply any of this",
        "blocker_5": "I was charming and social before that relationship — what I need is not a course, I need to remove the damage she did",
        "jtbd_type_1": "Social",
        "jtbd_1": "Be someone my friends recognise again — have opinions, take up space, be the same person whether I am with someone or completely alone",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Have something that is mine — a way of being in the world that isn't defined by or in reaction to her",
        "jtbd_type_3": "Functional",
        "jtbd_3": "Re-engage with the interests I abandoned for that relationship and have the social confidence to re-enter them without feeling like an outsider",
        "jtbd_type_4": "Emotional",
        "jtbd_4": "Stop the automatic self-censoring that became a habit — say what I think, take up space, and not apologize for it",
        "jtbd_type_5": "Social",
        "jtbd_5": "Have a reputation among new people built entirely by me — not inherited from who I was in that relationship",
    },
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Redundancy or Firing",
        "trigger_description": "Lost a job that was load-bearing for identity. Confidence in his own presence and judgment is shattered alongside professional status.",
        "timing_window": "3–9 months post job loss",
        "buyable_window": "3–9 months",
        "sweet_spot_months_post_event": "4–7 months",
        "reddit_communities": "r/careerguidance, r/selfimprovement, r/AskMen",
        "search_queries": "how to rebuild confidence after job loss, how to reinvent yourself, how to stop feeling worthless after redundancy",
        "content_channels": "Professional development and self-improvement content",
        "converting_hook": "Competence-confidence reframe — your skills are real. What failed was how you were presenting them and yourself.",
        "testimonial_type": "Getting made redundant was humiliating. It also forced me to realise I'd been hiding behind my job title for a decade.",
        "ad_campaign_angle": "Target men in career transition 3–9 months post redundancy via LinkedIn and self-improvement channels",
        "landing_page_angle": "You didn't lose what you know. You lost what was hiding the rest of you.",
        "product_fit": "Same product — slight overlap with Segment C on professional confidence",
        "special_notes": "Avoid overselling professional outcomes — this segment needs identity work first, career results second",
        "blocker_1": "What I need is a new job — not a course to work on my personality while I have no income",
        "blocker_2": "I used my job title to feel status and purpose — building charisma feels hollow when the thing that validated me is gone",
        "blocker_3": "Confidence is something you earn through achievement — I can't fake my way to it while I'm failing professionally",
        "blocker_4": "This is the wrong investment right now — every pound I spend here is a pound not going into retraining or interview prep",
        "blocker_5": "Charisma development is a luxury for when the basics are in order — I need to fix the fundamentals first",
        "jtbd_type_1": "Social",
        "jtbd_1": "Walk into a room where nobody knows my job title and still feel like somebody worth talking to — not hollowed out without the thing that used to define me",
        "jtbd_type_2": "Functional",
        "jtbd_2": "Interview in a way that puts the right kind of pressure on the room — confidence I'm choosing to project, not status borrowed from a title",
        "jtbd_type_3": "Emotional",
        "jtbd_3": "Separate my identity from my job title so that losing one doesn't mean losing the other — own who I am regardless of what I do",
        "jtbd_type_4": "Social",
        "jtbd_4": "Have my friends and network still see me as someone with weight and presence — not someone who lost their footing and is scrambling",
        "jtbd_type_5": "Functional",
        "jtbd_5": "Build a social life that doesn't revolve around work connections — people who know me as a person, not a role",
    },
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Geographic Relocation",
        "trigger_description": "Moved to a new city — existing social network gone overnight. Forced to build from zero with none of the familiar scaffolding.",
        "timing_window": "Immediate to 6 months post move",
        "buyable_window": "0–6 months",
        "sweet_spot_months_post_event": "1–3 months post move",
        "reddit_communities": "r/socialskills, r/moving, city-specific subreddits, r/AskMen",
        "search_queries": "how to make friends as an adult man, how to build a social circle in a new city, how to meet people as a grown man",
        "content_channels": "Social skills and self-improvement channels",
        "converting_hook": "Clean slate as opportunity — the best possible moment to build the version of yourself you've always wanted to be",
        "testimonial_type": "Moving cities at 33 was terrifying. It was also the first time I built a social life that actually reflected who I wanted to be.",
        "ad_campaign_angle": "Target recent movers via geographic life event targeting on Meta",
        "landing_page_angle": "You moved cities. This is your window to move identities too.",
        "product_fit": "Strong convergence point between Segment A and B — both arrive here via different routes",
        "special_notes": "Life event targeting on Meta is precise for this trigger. High intent moment.",
        "blocker_1": "Charisma I learn from a course will feel scripted — and people in a new city with no prior context will see straight through it",
        "blocker_2": "In a new city everyone already has their social circles — all the charisma in the world doesn't open groups that are already closed",
        "blocker_3": "The people I need to meet here are professionals with demanding lives — they don't have time to become friends with strangers no matter how charming",
        "blocker_4": "I've moved before and it got easier on its own once I settled in — I don't need to invest in this, I just need to give it time",
        "blocker_5": "A course takes weeks to work through — by the time I've finished it the critical early window for first impressions will be over",
        "jtbd_type_1": "Functional",
        "jtbd_1": "Have people in this city who would actually text me on a Friday — a real circle, not surface-level work acquaintances — within three months of arriving",
        "jtbd_type_2": "Social",
        "jtbd_2": "Be known in this new environment as someone interesting and worth knowing before I've had to fight to prove it",
        "jtbd_type_3": "Emotional",
        "jtbd_3": "Stop feeling like a stranger in a city I chose to move to and start feeling like someone who belongs here",
        "jtbd_type_4": "Functional",
        "jtbd_4": "Have a repeatable approach for converting acquaintances into genuine connections — not just hoping circumstances bring people together",
        "jtbd_type_5": "Social",
        "jtbd_5": "Build a reputation in this city in the first six months — because first impressions are the ones that stick",
    },
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Kids Leaving Home",
        "trigger_description": "Was a father for 18–22 years — identity built entirely around that role. Last child leaves and the defining structure of his adult life is gone.",
        "timing_window": "3–12 months after last child leaves",
        "buyable_window": "3–9 months",
        "sweet_spot_months_post_event": "5–7 months",
        "reddit_communities": "r/AskMenOver40, r/AskMenOver50, empty nester communities, r/Divorce",
        "search_queries": "who am I after kids leave home, how to start over at 50, how to meet people in your 50s, empty nest identity",
        "content_channels": "Midlife reinvention content, life coaching channels",
        "converting_hook": "Legacy reframe — everything you built as a father is preparation for who you become next.",
        "testimonial_type": "My youngest left for university and I realised I hadn't made a decision for myself in 20 years. That was a gift wrapped in terror.",
        "ad_campaign_angle": "Target men 47–58 in the empty nest transition phase via age and life event targeting",
        "landing_page_angle": "You spent 20 years building someone else. Now it's your turn.",
        "product_fit": "Same product — older demographic may prefer cohort or live vs self-paced",
        "special_notes": "High disposable income segment. Higher price point tolerance than younger cohorts.",
        "blocker_1": "This course is built for men trying to attract women in their 30s — it has nothing to say to a 52-year-old man who just needs to figure out who he is now",
        "blocker_2": "I've spent 20 years being dad — I genuinely don't know if the person I was before that is still in there or if he's just gone",
        "blocker_3": "People my age have known each other for decades — there is no room for a new person in established social circles at 52",
        "blocker_4": "I don't want to date right now, I want to have a life — charisma courses are designed for men who want to attract women not men who just want to feel alive again",
        "blocker_5": "Self-improvement at 52 has an expiry date — whatever I build now I'll only have for a limited number of years before it starts to matter less",
        "jtbd_type_1": "Functional",
        "jtbd_1": "Fill the next six months with things I actually chose — not obligations or killing time but evenings and weekends with people I want to know",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Feel like the most interesting chapter of my life might still be ahead of me — not like I'm already in the epilogue",
        "jtbd_type_3": "Social",
        "jtbd_3": "Build a social life that is entirely mine — not built around school runs, parent groups, or the world my marriage created",
        "jtbd_type_4": "Functional",
        "jtbd_4": "Have a real answer to 'what do you do outside of work' — interests, friends, and a life I can describe with genuine enthusiasm",
        "jtbd_type_5": "Emotional",
        "jtbd_5": "Stop dreading Sunday evenings when the house is quiet and start having something to actually look forward to instead",
    },
    {
        "segment_id": "B",
        "segment_name": "Ruptured Man",
        "market_share_pct": "50%",
        "baseline_description": "Had confidence or a life structure that masked the gap. A specific event collapsed the structure and left him socially exposed for the first time.",
        "core_question": "How do I become myself again — but better this time?",
        "trigger_type": "Left Religious or Ideological Community",
        "trigger_description": "Entire social world was built on a community that is now gone. Identity and belonging collapsed simultaneously.",
        "timing_window": "6–18 months post exit",
        "buyable_window": "6–18 months",
        "sweet_spot_months_post_event": "9–15 months",
        "reddit_communities": "r/exmormon, r/exchristian, r/exjw, r/atheism, community exit subreddits",
        "search_queries": "how to make secular friends, how to build social skills without religion, how to meet people outside church",
        "content_channels": "Secular self-improvement content",
        "converting_hook": "Secular belonging framing — connection and presence are learnable skills not divine gifts.",
        "testimonial_type": "I left my church at 31 and realised every social skill I had was built for that one context. I had to learn how to actually connect with people.",
        "ad_campaign_angle": "Target men in ex-religious communities 6–18 months post exit",
        "landing_page_angle": "You built your social world on faith. Here's how to build it on skill.",
        "product_fit": "Same product — strong community and belonging modules especially relevant",
        "special_notes": "Messaging must not mock religion. Focus on building forward, not criticising the past.",
        "blocker_1": "Learning connection from a structured programme feels like replacing one set of rules with another — I just escaped a system that told me how to behave",
        "blocker_2": "My entire social world was inside that community — even if I learn new skills, I've lost everyone I knew and have nowhere to apply them",
        "blocker_3": "The reason I was good at connecting inside the church was shared beliefs — I don't know how to connect with people who don't share my framework",
        "blocker_4": "People who haven't been through what I've been through will find my background weird — and no amount of charisma bridges that gap",
        "blocker_5": "I don't know who I am without the moral framework I grew up in — building charisma feels premature when I'm still figuring out my basic values",
        "jtbd_type_1": "Social",
        "jtbd_1": "Walk into a room of strangers who share none of my history and have them genuinely want to talk to me again — not because of what group I belong to but because of who I am",
        "jtbd_type_2": "Functional",
        "jtbd_2": "Build friendships outside the community I left that can actually survive the knowledge of where I came from",
        "jtbd_type_3": "Emotional",
        "jtbd_3": "Stop feeling like an imposter in secular social spaces — feel genuinely at home somewhere that has nothing to do with who I used to be",
        "jtbd_type_4": "Social",
        "jtbd_4": "Have a way to meet and connect with people that doesn't rely on belonging to an institution — skills that work in any room, any context",
        "jtbd_type_5": "Emotional",
        "jtbd_5": "Own the story of where I've been in a way that makes me more interesting to people, not less — stop treating my past as something to hide",
    },
    # ── SEGMENT C: PROFESSIONAL OPTIMIZER ──────────────────────────────────────────
    {
        "segment_id": "C",
        "segment_name": "Professional Optimizer",
        "market_share_pct": "10%",
        "baseline_description": "Already socially and professionally successful — gym-disciplined, career-strong, solid male friendships. Has optimized everything except intimate connection. Treats charm as the last untrained muscle.",
        "core_question": "I've built everything — why is this the one area where more effort doesn't equal more results?",
        "trigger_type": "New Love Interest",
        "trigger_description": "Meets someone he's genuinely attracted to and realizes his usual approach — confident, composed, achievement-signaling — creates interest but not lasting attraction. Emotional availability and real presence are the missing piece.",
        "timing_window": "Immediate — within 2–4 weeks of first meeting",
        "buyable_window": "0–3 weeks",
        "sweet_spot_months_post_event": "1–2 weeks",
        "reddit_communities": "r/dating_advice, r/AskMen, r/selfimprovement, r/datingoverthirty",
        "search_queries": "why do women lose interest after meeting a great guy, how to be more emotionally available, why women say I'm hard to read, how to create deeper attraction",
        "content_channels": "Dating coaches who use performance and optimization language, fitness-adjacent self-improvement channels",
        "converting_hook": "Precision reframe — it's not about doing more, it's about showing up differently in the one context where your usual approach creates distance",
        "testimonial_type": "I had an incredible first date and she said I seemed like I was interviewing her. I understood exactly what she meant.",
        "ad_campaign_angle": "Target high-achieving men 28–42 actively dating and consuming self-improvement content simultaneously",
        "landing_page_angle": "Your confidence works everywhere except here. Here's why — and what to do instead.",
        "product_fit": "Same product as Attraction Plateau — performance and optimization framing, not healing. Higher price tolerance. These two triggers often belong to the same man.",
        "special_notes": "Pairs naturally with Attraction Plateau. Often the same man experiences both. Do not use vulnerability or healing language — use precision, calibration, performance.",
        "blocker_1": "The way I normally operate — confident, composed, in control — is exactly what makes me seem emotionally unavailable to women worth having",
        "blocker_2": "With women I'm actually attracted to I become calculated and stilted — I'm confident everywhere else, but with her I'm performing instead of being present",
        "blocker_3": "If I study how to be more attractive to her it means I'm not being authentic — and she'll eventually see through the effort",
        "blocker_4": "I've been on first dates before and they go well, but she always labels me as 'too intense' or 'not emotionally available' — this is a pattern, not a skill gap",
        "blocker_5": "A course will give me techniques to seem warmer but won't change the underlying reason I shut down with women I actually care about — that might need therapy, not training",
        "jtbd_type_1": "Functional",
        "jtbd_1": "Have a clear way to transition from 'impressive man she met' to 'man she can't stop thinking about' — within the first 2–3 interactions, not after months of orbiting",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Feel genuinely relaxed and present with a woman I find exceptional — not performing the version of myself I think she wants to see",
        "jtbd_type_3": "Social",
        "jtbd_3": "Be the man she tells her friends about — not just 'this successful guy I've been seeing' but someone who actually makes her feel something",
        "jtbd_type_4": "Functional",
        "jtbd_4": "Know specifically what to do differently in the next interaction with her — a precise adjustment to how I show up, not generic dating advice",
        "jtbd_type_5": "Emotional",
        "jtbd_5": "Stop the internal conflict between wanting to be genuine and wanting to make a strong impression — feel like those two things are the same thing",
    },
    {
        "segment_id": "C",
        "segment_name": "Professional Optimizer",
        "market_share_pct": "10%",
        "baseline_description": "Already socially functional — wants elite-level presence for high-stakes professional or personal contexts. Treats charisma as a skill to train, not a personality deficiency to fix.",
        "core_question": "I've optimized everything else — why is this the one area where more effort doesn't equal more results?",
        "trigger_type": "Attraction Plateau",
        "trigger_description": "Successful in fitness, career, and male friendships. Dates well initially but women consistently pull back after 4–8 weeks. He has approached dating like a project to optimize — research, apps, profile work — and it still doesn't convert. Realizes the gap is not effort or information, but something in how he shows up emotionally.",
        "timing_window": "Ongoing — crystallises after 2nd or 3rd time the same pattern repeats",
        "buyable_window": "Immediate once pattern is named",
        "sweet_spot_months_post_event": "0–4 weeks after pattern recognition",
        "reddit_communities": "r/selfimprovement, r/dating_advice, r/AskMen, r/TheRedPill adjacent but skeptical",
        "search_queries": "why do women lose interest after a few weeks, how to keep a woman interested, why am I good on dates but she pulls away, why do I keep attracting avoidant women",
        "content_channels": "Fitness-adjacent self-improvement channels, dating coaches who use gym/discipline analogies, Andrew Huberman adjacent content",
        "converting_hook": "Muscle gap reframe — you've trained everything else. This is the one muscle you haven't touched.",
        "testimonial_type": "I had my life completely together and couldn't keep a woman interested past month two. The problem wasn't my life — it was how I was showing up in it.",
        "ad_campaign_angle": "Target high-achieving men 28–42 who consume fitness + self-improvement content and dating advice simultaneously",
        "landing_page_angle": "You train everything. This is the one muscle you haven't built yet.",
        "product_fit": "Different product framing from A and B — emphasize performance and optimization, not healing or rebuilding. Higher price tolerance.",
        "special_notes": "This man does not identify with men who lack confidence. Frame as elite optimization, not gap-filling. Gym and performance language converts well with this segment.",
        "blocker_1": "I approach everything systematically and it works — but the more I treat dating like a project to optimize, the worse it seems to go, so maybe this isn't learnable",
        "blocker_2": "I've read the books and understand the theory — but knowing what to do intellectually and doing it in the moment are completely different things, and that gap might not be closeable",
        "blocker_3": "Every woman I date eventually says I'm closed off or hard to read — this isn't a skill I'm missing, it's something in my character that is genuinely difficult to change",
        "blocker_4": "Charisma courses are designed for men with no social confidence — I have plenty of confidence, just not in this specific kind of vulnerability, and I doubt a course covers that",
        "blocker_5": "If I start acting warmer or more openly charming it will feel inconsistent with who I am at work and with my male friends — and I'll seem like I'm performing for women",
        "jtbd_type_1": "Functional",
        "jtbd_1": "Keep a woman interested past month three — not by performing better on dates but by being genuinely present in a way that makes her want to come back",
        "jtbd_type_2": "Emotional",
        "jtbd_2": "Stop feeling like my personality — which works everywhere else — is somehow broken in intimate contexts, and understand what is actually going on",
        "jtbd_type_3": "Social",
        "jtbd_3": "Be seen by a woman I respect as both strong and warm — not one or the other, not someone who is trying to be one while the other is clearly missing",
        "jtbd_type_4": "Functional",
        "jtbd_4": "Identify the specific moment where women start to pull back and understand what I'm doing or not doing that causes it — so I can change the pattern, not just the person",
        "jtbd_type_5": "Emotional",
        "jtbd_5": "Stop approaching relationships like another project to optimize and actually enjoy being with someone — feel like a man in a relationship, not a manager running a process",
    },
]

df = pd.DataFrame(ROWS)
out = "/Users/viktoriia.shyrokova/Documents/Attachment-styles funnel/reddit-research/male_charisma_mastery.csv"
df.to_csv(out, index=False, encoding="utf-8-sig")
print(f"Written {len(df)} rows to {out}")
print(f"Columns ({len(df.columns)}): {list(df.columns)}")
print(f"\nSegment distribution:\n{df.groupby(['segment_id','trigger_type']).size().to_string()}")
